### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by tskorupka** [artilleryio/artillery-xml-capture#1]
Hello there, just ran command `npm install -g artillery-xml-capture`

With such errors

[https://pastebin.com/y2WSDnru](url) <- CLI
[https://pastebin.com/s3iA8AE0](url) <- Log file

npm v. 4.5.0
nodejs v. 6.9.5

**Comment by subhojit777** [comment]
+1

I am also having the same problem.

```
../../nan/nan.h:592:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:598:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:603:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:609:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
```

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/www/blah/scripts/artillery/node_modules/libxmljs
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN rolex@1.0.0 requires a peer of bower@* but none was installed.
npm WARN artillery-testing@1.0.0 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "artillery-xml-capture"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.17.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.17.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/www/blah/scripts/artillery/npm-debug.log
```

**Comment by tskorupka** [comment]
Just updated nodejs to latest version and its working.
W dniu pon., 24.04.2017 o 19:00 Subhojit Paul <notifications@github.com>
napisał(a):

**Comment by subhojit777** [comment]
@tskorupka have you updated it to 6.10.2 or 7.9.0 ?

**Comment by tskorupka** [comment]
To 7.x

Pozdrawiam,
Tomasz Skorupka.
Wysłano z iPhone.

Dnia 24.04.2017 o godz. 19:09 Subhojit Paul <notifications@github.com> napisał(a):

**Comment by subhojit777** [comment]
It is still not working for me

```
../../nan/nan.h:592:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:598:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:603:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:609:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:1933:15: warning: 'SetAccessor' is deprecated [-Wdeprecated-declarations]
  return obj->SetAccessor(
```

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/subhojit/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/node-gy
p/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/subhojit/.nvm/versions/node/v7.9.0/bin/node" "/Users/subhojit/.nvm/versions/node/v7.9.0/lib/node_modu
les/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/www/blah/scripts/artillery/node_modules/libxmljs
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN rolex@1.0.0 requires a peer of bower@* but none was installed.
npm WARN artillery-testing@1.0.0 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/subhojit/.nvm/versions/node/v7.9.0/bin/node" "/Users/subhojit/.nvm/versions/node/v7.9.0/bin/npm" "instal
l" "--save-dev" "artillery-xml-capture"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! libxmljs@0.17.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.17.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/subhojit/.npm/_logs/2017-04-24T17_36_44_930Z-debug.log
```

**Comment by hassy** [comment]
Yes these are all `libxmljs`-related build errors (and the reason this Artillery module was extracted from the main distribution as well). Sometimes upgrading Node.js helps, sometimes you need to install missing development packages for libxml etc. There's no known solution that works for everybody unfortunately.
